rvm:
  - "1.9.2"
  - "1.9.3"

before_script:
  - "mv config/database.example.yml config/database.yml"
  - "mv config/email.example.yml config/email.yml"

script:
  - "bundle exec rake db:create db:migrate db:test:clone spec"

branches:
  only:
    - master
