rvm:
  - "1.9.2"
  - "1.9.3"

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

before_script:
  - "script/db_setup"
  - "mv config/email.example.yml config/email.yml"

script:
  - "bundle exec rake db:create db:migrate db:test:prepare spec"

branches:
  only:
    - master
