rvm:
  - "1.9.2"
  - "1.9.3"
  - "jruby-19mode"
  - "rbx-19mode"

env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite

before_script:
  - "script/db_setup"
  - "mv config/settings.example.yml config/settings.yml"

script:
  - "COVERAGE=on bundle exec rake db:create db:migrate db:test:prepare spec"

branches:
  only:
    - master
