rvm:
  - "1.9.2"
  - "1.9.3"

env:
  - DB=mysql
  - DB=sqlite

before_script:
  - "mv config/database.#{ENV{'DB']}.yml config/database.yml"
  - "mv config/email.example.yml config/email.yml"

script:
  - "bundle exec rake db:create db:migrate db:test:prepare spec"

branches:
  only:
    - master
