production:
  adapter: mysql2
  database: troch
  username: troch
  password: troch
  encoding: utf8
  host: localhost
  reconnect: true

# for development
development:
  adapter: mysql2
  database: troch_development
  username: troch_development
  password: troch_development
  encoding: utf8
  host: localhost
  reconnect: true

test:
  adapter: mysql2
  database: troch_test
  username: troch_test
  password: troch_test
  encoding: utf8
  host: localhost
