production:
  adapter: mysql2
  database: troch
  username: root
  password:
  encoding: utf8
  host: localhost
  reconnect: true
  socket: /var/run/mysqld/mysqld.sock

# for development
development:
  adapter: mysql2
  database: troch_development
  username: root
  password:
  encoding: utf8
  host: localhost
  reconnect: true
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  database: troch_test
  username: root
  password:
  encoding: utf8
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
