production:
  adapter: mysql2
  database: troch
  username: troch
  password: troch
  encoding: utf8
  host: localhost
  reconnect: true

# for development
development:
  adapter: mysql2
  database: troch_development
  username: root
  password:
  encoding: utf8
  host: localhost
  reconnect: true

test:
  adapter: mysql2
  database: troch_test
  username: root
  password:
  encoding: utf8
  host: localhost
