production:
  adapter: postgresql
  encoding: unicode
  database: troch
  pool: 5
  username: troch
  password: troch
  min_messages: WARNING

# for development
development:
  adapter: postgresql
  encoding: unicode
  database: troch_development
  pool: 5
  username: postgres
  password:
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: troch_test
  pool: 5
  username: postgres
  password:
  min_messages: WARNING
