default:
  from: 'troch@example.com'

email:
  address:        'smtp.example.com'
  port:           25
  domain:         'example.com'
  user_name:      'troch@example.com'
  password:       'password'
