#!/usr/bin/env ruby

require File.expand_path('../../config/application', __FILE__)
Rails.application.require_environment!

ENV['RAILS_ENV'] ||= 'production'

unless Resque.workers.blank?
  Resque.workers.each do |w|
    w.prune_dead_workers
  end
end
