#!/usr/bin/env ruby

require File.expand_path('../../config/application', __FILE__)
Rails.application.require_environment!

require 'time'

def within_1hour?(record_time)
  if Time.parse(record_time) < Time.now - 1 * 60 * 60
    false
  else
    true
  end
end

def get_record_time
  file = open("#{Rails.root}/public/record_time")
  record_time = file.first
  file.close

  record_time
end

users = User.find(:all, :conditions => {:summary => true})

unless users.blank?
  while true
    sleep 60 * 60

    begin
      record_time = get_record_time
      if !record_time.nil? && within_1hour?(record_time)
        puts "Troch-worker is running normally. #{Time.now}"
      else
        puts "Troch-worker has broken down! #{Time.now}"

        puts 'Restart troch-worker.'
        `/etc/init.d/troch-worker restart`
        sleep 10 * 60

        record_time = get_record_time
        if !record_time.nil? && within_1hour?(record_time)
          puts "Troch-worker is restarted normally #{Time.now}"
        else
          puts "Troch-worker cannot be restarted! #{Time.now}"
          users.each do |user|
            NoticeMailer.sendmail_health_check(user).deliver
          end
        end
      end
      file.close
    rescue
    end
  end
end
